[package]
name = "shallenge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.7"
jemallocator = "0.5.4"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
rayon = "1.10.0"
sha2 = "0.10.8"

[profile.release]
lto = "fat"
opt-level = 3
overflow-checks = false
codegen-units = 1
panic = "abort"
